### ISSUE TITLE
Update for VS 2017

### ISSUE THREAD

**Issue by ageisen2000** [reduckted/pretty-listing-fixer#1]
What can I do to enable this addon for VS 2017

**Comment by reduckted** [comment]
I haven't used VS 2017 much yet, so I wasn't sure if this extension was still needed. By the sounds of it, it's still needed, so I'll make a version for VS 2017 soon. 😄

**Comment by ageisen2000** [comment]
Thank you!

**Comment by reduckted** [comment]
I've just published a new version with Visual Studio 2017 support! ✨
